### ISSUE TITLE
No Instructions on How to Mark-Up List Items

### ISSUE THREAD

**Issue by sarahhtbarton** [learn-co-curriculum/phase-0-html-experiencing-html-lab#1]
Hi, this lesson is missing instructions on how to mark-up list items. It tells you to wrap each line with `<li>` and `</li>`, but no instructions on where or how to do so (in the terminal? in chrome?). It then tells you to go back to the "viewing page," but leaves out what page you're supposed to be on in the first place. Confusing and needs clarification. 

This is the part of the lesson I'm referring to:

Marking-Up List Items
OK, we've reached the critical moment. We're going to tell the browser that these bits of letters represent list items. To do so we "wrap" each line with `<li>` and `</li>`. For example: `<li>`"A Forest"`</li>`

<li>"Love Will Tear Us Apart"</li>
<li>"Bela Lugosi's Dead"</li>
<li>"A Forest"</li>
<li>"Nine While Nine"</li>
<li>"Girlfriend In a Coma"</li>
Flip back to the viewing tab and refresh the page. You should see something like the following:

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The lab has been updated to clarify the instructions.

Thanks for contributing to the Flatiron School curriculum! 💙
