### ISSUE TITLE
Fork button has the wrong link

### ISSUE THREAD

**Issue by Zio-4** [learn-co-curriculum/phase-0-html-experiencing-html-lab#10]
The fork button does not take you to GitHub. It takes you to https://base.flatironschool.com/.

**Comment by bal360** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
