### ISSUE TITLE
bundle command returns "could not locate gemfile" error

### ISSUE THREAD

**Issue by JonnyOrtiz-source** [learn-co-curriculum/phase-0-html-experiencing-html-lab#17]

**Comment by JonnyOrtiz-source** [comment]
`jonnyortiz@Jonnys-MacBook-Air phase-0-html-experiencing-html-lab % bundle
Could not locate Gemfile`

**Comment by JonnyOrtiz-source** [comment]
I entered bundle init, then bundle.
jonnyortiz@Jonnys-MacBook-Air phase-0-html-experiencing-html-lab % bundle init
Writing new Gemfile to /Users/jonnyortiz/Flatiron/Development/code/prework/phase-0-html-experiencing-html-lab/Gemfile
jonnyortiz@Jonnys-MacBook-Air phase-0-html-experiencing-html-lab % bundle
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

**Comment by lizbur10** [comment]
Hi again! Same issue here - see my previous comments 💙
