### ISSUE TITLE
Having trouble submitting assignment

### ISSUE THREAD

**Issue by NKP-jpg** [learn-co-curriculum/phase-0-html-experiencing-html-lab#4]
I am not sure if all of the HTML steps are to be done in the terminal or in VS Code.  If in the terminal, How do I add lists to the HTML folder in the terminal?

**Comment by lizbur10** [comment]
Hi there! Thank you for bringing this issue to our attention. The assignment has been updated to clarify the instructions so I'm going to close this issue. If you don't believe the problem has been fixed, please feel free to reopen it.

Thanks for contributing to the Flatiron School curriculum. 💙
