### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by brandonefields** [learn-co-curriculum/phase-0-html-experiencing-html-lab#9]
As noted above, the browser doesn't know that items on new lines means "items in a list." Browsers ignore when HTML has is split onto new lines. We cover why a little later in this README. Since the browser doesn't know we intend this to be a list and since browsers ignore when content is split onto different lines, it displays all the content on one line. Not what we wanted.

"Browsers ignore when HTML has is split onto new lines" correct ???

**Comment by lizbur10** [comment]
Hi there! Thanks for spotting this and posting feedback. The content has been updated to correct the error 💙
